version: "3.8"
services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"
    env_file:
      - .env

  api:
    build: .
    command: sh -c "./wait-for-db.sh && npm run dev"
    volumes:
      - .:/app
    ports:
      - "${PORT}:3000"
    environment:
      DB_HOST: db # Docker override
      PORT: ${PORT}
      NODE_ENV: ${NODE_ENV}
      JWT_EXPIRATION: ${JWT_EXPIRATION}
      JWT_PRIVATE_KEY_PATH: ${JWT_PRIVATE_KEY_PATH}
      JWT_PUBLIC_KEY_PATH: ${JWT_PUBLIC_KEY_PATH}
      JWT_ALGORITHM: ${JWT_ALGORITHM}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_DIALECT: ${DB_DIALECT}
    depends_on:
      db:
        condition: service_healthy

volumes:
  db-data:
