services:
  app:
    build: .
    container_name: infernode-app
    ports:
      - "${API_HOST:-3000}:3000"
    env_file: .env
    environment:
      - NODE_ENV=${NODE_ENV}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    depends_on:
      redis:
        condition: service_started
      postgres:
        condition: service_healthy
    volumes:
      - ./src/:/app/src
      - /app/keys
      - ./tsconfig.json:/app/tsconfig.json


  # ask for port configuration to Sir. Adriano
  redis:
    image: redis:latest
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"

  postgres:
    image: postgres:latest
    restart: unless-stopped
    container_name: infernode_db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    env_file: .env
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: "exit 0"

volumes:
  postgres_data:
